######################## default configuration ####################
baseURL = "https://examplesite.com"
title = "GoFolium | Hugo Publication Template"
theme = "gofolium"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/particles/particles.min.js"
[[params.plugins.js]]
link = "plugins/particles/stats.min.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "home"
URL = "home"
weight = 1

[[menu.main]]
name = "about"
URL = "about"
weight = 2

[[menu.main]]
name = "publication"
URL = "publication"
weight = 3
  
[[menu.main]]
name = "talk"
URL = "talk"
weight = 4
  
[[menu.main]]
name = "project"
URL = "project"
weight = 5
  
[[menu.main]]
name = "blog"
URL = "blog"
weight = 6
  
[[menu.main]]
name = "contact"
URL = "contact"
weight = 7


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "" # your id

# body particles
particles = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "contact"
link = "contact"
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"